version: '2'
services:
    service:
        build: .
        env_file: .env
        environment:
            - PYTHONUNBUFFERED=1
        command: flask run --host=0.0.0.0 --port=5000 --reload
        tty: true
        volumes:
            - .:/app
        ports:
            - "5000:5000"
